run: history.o tokenizer.o gui.o main.o
	cc history.o tokenizer.o gui.o main.o -o run

history.o: history.c
	cc -c history.c

tokenizer.o: tokenizer.c
	cc -c tokenizer.c

gui.o: gui.c
	cc -c gui.c

main.o: main.c
	cc -c main.c
